manifest:
  package: rew.gtk
  private: false
exec:
  entry: main.coffee
assets:
  icon: assets/icon.png
  folder: ./assets
install:
  requirements: []
  build: 
    file: entry
    remove: true
  commandses:
    - sh $installPath/install.sh
